class DbError < ActiveRecord::Base
   
  set_table_name :errors
   
  def related
    self.class.find_all_by_message(message, :conditions=>["id != ?", id])
  end  

  def description
    message.to_s + " generated by controller #{controller.to_s} / action #{action.to_s}"
  end
  
end